image: "python:3.8" 

#commands to run in the Docker container before starting each job.
before_script:
  - python3 --version
  
# different stages in the pipeline
stages:
  - Test
  
pytest:
  stage: Test
  script:
  - pip3 install -r requirements.txt
  - export MPLBACKEND="agg"
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - coverage run -m pytest
  - coverage report
