image: "python:3.8" 

#commands to run in the Docker container before starting each job.
before_script:
  - python3 --version
  
# different stages in the pipeline
stages:
  - Test
  
pytest:
  stage: Test
  script:
  # - export PYTHONPATH="$PYTHONPATH:."
  # - python -c "import sys;print(sys.path)"
  - pip3 install -r requirements.txt
  - pytest
  # - coverage run -m pytest
  # - coverage report
