image: "python:3.8" 

#commands to run in the Docker container before starting each job.
before_script:
  - python3 --version
  
# different stages in the pipeline
stages:
  - Test
  
pytest:
  stage: Test
  script:
  - pip3 install pytest==6.1.1
  - pip3 install coverage==5.3
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - pytest
  # - coverage run -m pytest
  # - coverage report
