name: div-phil-alim
channels:
  - conda-forge
dependencies:
  - PyQt
  - beautifulsoup4 
  - ete3 = 3.1.2
  - numpy 
  - PyVirtualDisplay = 1.3.2
  - requests = 2.24.0
  - selenium = 3.141.0
  - xlrd = 1.2.0
  - six = 1.15.0
  - pip
  - pip :
        - webdriver-manager